-- Question 3: For all cases where A is friends with B, and B is friends with C, add a new friendship for the pair 
-- A and C. Do not add duplicate friendships, friendships that already exist, or friendships with oneself.
--.read data.sql